name:                {{ cookiecutter.project_name }}
version:             0.1.0.0
github:              "{{ cookiecutter.github_owner }}/{{ cookiecutter.project_name }}"
license:             BSD-3-Clause
author:              "{{ cookiecutter.group_name }}"
maintainer:          "{{ cookiecutter.mail }}"
copyright:           "{% now 'utc', '%Y-%M-%D' %} {{ cookiecutter.group_name }}"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/{{ cookiecutter.github_owner }}/{{ cookiecutter.project_name }}#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  {{ cookiecutter.project_name }}-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Tmp

tests:
  {{ cookiecutter.project_name }}-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Tmp
